### ISSUE TITLE
Error message registering new branch from front end

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#112] opened 2014-02-07 14:37 UTC
I am trying to help set up TS Rotterdam. Caroline said the best way was if they filled in the 'start a trade school' form on this page http://tradeschool.coop/start-a-tradeschool/
And then work on the pending branch from the admin end. The Rotterdam organiser filled in the form and got this error message:

IntegrityError at /start-a-tradeschool/

(1062, "Duplicate entry 'Nienke Binnendijk' for key 'username'")
Request Method: POST
Request URL:    http://tradeschool.coop/start-a-tradeschool/
Django Version: 1.5.1
Exception Type: IntegrityError
Exception Value:  
(1062, "Duplicate entry 'Nienke Binnendijk' for key 'username'")
Exception Location: /opt/projects/tse/eggs/MySQL_python-1.2.3-py2.7-linux-x86_64.egg/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:  /usr/bin/python
Python Version: 2.7.3

**Comment by carolinewoolard** [comment] 2014-02-07 14:40
It shows up in the back end at http://tradeschool.coop/admin/tradeschool/pendingbranch/ but we need a feedback loop to let possible organizers know that their request to start a branch is working

**Comment by orzubalsky** [comment] 2014-02-07 20:46
I'm closing this since the problem is actually the form being submitted twice.

**Closed as completed by orzubalsky** 2014-02-07 20:46 UTC
Labels: type: bug, prio: normal
