### ISSUE TITLE
Add Barter Items - New Class

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#89] opened 2014-01-30 15:14 UTC
http://awesomescreenshot.com/0012a3y53f

I must have deleted some classes and really need to add new ones. I am stumped on how to add barter items to new classes.

It just says Title.

**Comment by orzubalsky** [comment] 2014-01-30 15:16
Isn't this the same bug as not being able to add barter items?

**Comment by orzubalsky** [comment] 2014-01-30 15:17
Also, a feature request would be something that does not currently exist in the system but that we would like to add. I'm removing that label just so things stay organized.

**Comment by brittanyukulele** [comment] 2014-01-30 15:17
WEll, there's two areas where it won't let add barter items. Here, and in the actual Barter Items page?

**Comment by brittanyukulele** [comment] 2014-01-30 15:20
Gotcha! Let me know if this shouldn't be two issues, but I wasn't sure since there's a few areas without the option to add/edit.

**Comment by orzubalsky** [comment] 2014-01-30 15:22
You're right. Both are caused by the same bug though, so I'm closing this one and will update #75.

Until I have time to fix this, you can add classes as if you were a teacher submitting a class:
1. As an admin, add the time slot that you would like the class to take place in.
2. As a "teacher", go to http://tradeschool.coop/indianapolis/class/add 
3. Fill in the form and submit it.
4. The class should be in the pending classes section of the admin.

**Closed as completed by orzubalsky** 2014-01-30 15:22 UTC
Labels: type: bug, prio: high
