### ISSUE TITLE
"Change Password" function not working

### ISSUE THREAD

**Issue by lpedante** [orzubalsky/tradeschool#152] opened 2014-04-14 18:10 UTC
Teacher's are having trouble getting into their accounts. they use the "Forgot Password" link, then get the Reset link and reset their password. Then, when they go to log in using the password they just created, it still locks them out. The correct usernames are being used so I don't know what's causing the problem..

![image](https://cloud.githubusercontent.com/assets/6611930/2698877/e8d4ed38-c3ff-11e3-9e74-ed467a7e58a3.png)

**Comment by dnephin** [comment] 2014-04-18 19:19
Hello, 

I tried this out with a local copy of the code. I believe the issue is not that Teachers can't change their password, the issue is that `Teacher`s are not created with `is_staff=True` which is what lets someone login to admin.  

From the comments it sounds like this was done on purpose, and only organizers are able to login.  I'll let someone more familiar with that comment on it. 

It should be an easy enough change if we wanted to add `is_staff=True` for teachers as well.

**Comment by lpedante** [comment] 2014-04-18 19:22
Thank you! I misunderstood the functionality. Since teachers aren't able to
log in, you can close this ticket. Thank you!

Leanne Pedante Design http://www.leannepedante.com/ | 323-532-0406
Trade School Los Angeles http://tradeschool.coop/losangeles/ | TSLA
on FBhttps://www.facebook.com/tradeschoolLA

**Comment by dnephin** [comment] 2014-04-20 21:17
@lpedante , I am not a collaborator (on the github project), so I can't close this ticket. I believe you can close it though

**Comment by lpedante** [comment] 2014-04-21 15:11
Sorry about that, Daniel! I'll close the ticket. Thank you!

Leanne Pedante Design http://www.leannepedante.com/ | 323-532-0406
Trade School Los Angeles http://tradeschool.coop/losangeles/ | TSLA
on FBhttps://www.facebook.com/tradeschoolLA

**Comment by dnephin** [comment] 2014-04-21 15:13
Thank you!

**Closed as completed** 2014-04-21 15:13 UTC
Labels: type: bug
